#!/bin/bash
set -u -e -C;
shopt -s nullglob;

function err { echo "$@" >&2; }
function warn { echo "$@" >&2; }

function ask_yN {
    local answer='';
    read -n 1 -s -p "$* [yN]" answer;
    if test "${answer}" = y; then
        echo yes;
        return 0;
    fi;
    echo no;
    return 1;
}

nl="${1:?missing arg1: min number of nodes}";
nu="${2:?missing arg2: max number of nodes}";
db="${3:?missing arg3: min balance}";

make testMatcher;
dir="g-${nl}-${nu}-${db}";
mkdir -p "${dir}";
log="${dir}/log";

if test -r "${log}"; then
    count="$(wc -l <"${log}")";
else
    cat <<EOF | tee "${log}";
# graph leftCount rightCount edgeCount
EOF
    count=0;
fi;


until read -t0.01 -n1 -s; do
    count="$((count + 1))";
    test "$count" -gt 5000 && exit 0;

    if test -e "${dir}/${count}"; then
        echo "Graph ${count} exists" >&2;
    else
        printf "%4i %4i %4i %6i\n" "${count}" $(./testMatcher mkgraph "${nl}" "${nu}" "${db}" "${dir}/${count}");
    fi;
done 2>&1 | tee -a "${log}";
