#!/bin/bash
set -u -e -C;
shopt -s nullglob;


dir='./tmp';
cpus="$(nproc)"


function err { echo "$@" >&2; exit 1; }
function req { test -x "$1" || err "missing: $1"; }

req dist/build/fgl/fgl
req dist/build/matcher/matcher
req dist/build/mkGraphs/mkGraphs




if test -d "$dir"; then
    echo "Using existing test data";
else

    cat <<EOF
----------------------------------------------------------------------
Generating random graphs...
EOF
    
    # Generate test data if $dir does not exist.

    # Large test: 2k graphs with up to 2000 nodes
    #dist/build/mkGraphs/mkGraphs "$cpus" "$dir" 2000 2000 >&2;

    # Small test: 500 graphs with up to 1k nodes
    #dist/build/mkGraphs/mkGraphs "$cpus" "$dir" 500 1000 >&2;

    # Tiny test: 200 graphs with up to 100 nodes
    dist/build/mkGraphs/mkGraphs "$cpus" "$dir" 200 100 >&2;

fi;


# data format: <graphId> <left> <right> <edges>
ls "$dir" | sed -rn 's:g([0-9]+)-([0-9]+)l-([0-9]+)r-([0-9]+)e.graph:\1 \2 \3 \4:p' >| "$dir"/nodes_edges.data


cat <<EOF
----------------------------------------------------------------------
Calculating matchings, do this in parallell...
EOF


for g in "$dir"/*.graph; do

    b="$(basename "$g" .graph)";

    for m in fgl matcher; do

        if test -e "$dir/$m.$b.time"; then
            echo "Skipping: $g";
        else
            echo "Running $m on $g";
            timeout -s9 30 /usr/bin/time \
              -o "$dir/$m.$b.time" \
              -f "%U %M" \
              "dist/build/$m/$m" "$g" \
              >| "$dir/$m.$b.out" \
              || rm -f "$dir/$m.$b.time" &
        fi;
        
        while test "$(jobs | grep -c Running)" -ge "$cpus"; do
            wait -n;
        done;

    done;
done;

wait && echo "Waiting for all jobs";



cat <<EOF
----------------------------------------------------------------------
Comparing all outputs...
EOF

for i in "$dir"/*.graph; do
    cmp "$dir"/{matcher,fgl}.$(basename "$i" .graph).out || true;
done;



cat <<EOF
----------------------------------------------------------------------
Aggregating timing...
EOF

for m in fgl matcher; do
    for f in "${dir}/${m}."*'.time'; do
        dat="$(sed -rn 's:[^.]*\.g([0-9]+)-([0-9]+)l-([0-9]+)r-([0-9]+)e:\1 \2 \3 \4:p' <<< "$(basename "$f" .time)")";

        echo "${dat} $(< $f)" >> "${dir}/timings.${m}";
    done;
    
done;



cat <<EOF
----------------------------------------------------------------------
Ok, timings are collected in \`${dir}/timings.*\`.  Calling gnuplot...

EOF

./scripts/plot </dev/null || echo 'gnuplot FAILED';



cat <<EOF
----------------------------------------------------------------------
You can edit \`scripts/plot\` and relaunch just that to plot the
same data in different output formats.

Done.
EOF
